promotion:
  /(master|main)/:
    - tag
    - npm_promotion
    - release_notes
    - bump_versions
  /(^release$|^preview$|^hotfix|^((?:[0-9]+\.)+[0-9]+)(-[a-zA-Z]{2,3}[0-9]+)?$)/:
    - npm_promotion
  default:
    - fail